### ISSUE TITLE
firebase lost connection (token 60 minutes)

### ISSUE THREAD

**Issue by biggiu** [Rupakpoddar/ESP32Firebase#2]
Hello and congratulations on your work.
I just discovered this library. I have been working so far with Mobizt's Firebase_ESP_Client. I encountered the problem of the token lifetime of up to 60 minutes in this library. Once the time expires, the connection to the Firebase database is lost and the procedure must be restarted. Is this a problem that also occurs in this library?
Thanks for the kind cooperation.
Best Regards.

**Comment by Rupakpoddar** [comment]
Hi @biggiu -- this library does not impose any such limitations.

**Comment by biggiu** [comment]
Thanks for the prompt response.
I'm starting to study your example to understand how to work with it.
The thing I noticed and I think I understand is that you don't use the API_KEY. It's right?
